[project]
title = "Pokemon Project"
version = "0.1.0"
port = 8501
slug = "pokemon-project"  
entrypoint = "hello.py"    

[branding]
name = "Pokemon Project"
logo = "images/pokeball.png"
favicon = "images/pokeIcon.ico"
primaryColor = "#F89624"

[data.pokemon_csv]
type = "csv"
path = "data/pokemon.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"